### ISSUE TITLE
誤字と違和感を感じた点

### ISSUE THREAD

**Issue by haruyama** [herumi/ango-src#1]
p 3: TLS3.0 に対する =>  SSL3.0に対する
p 8: まだ RSA の鍵についての説明がないので 1024ビットRSA ... といった単にビット数で鍵の強さが示されるわけではないものと AES が一緒に語られるのは違和感を与えそう. 直前までブロック暗号の話をしているし DES/AES を例にしたほうが適当か

p 13, 15: /dev/urandom を関数と呼ぶのは違和感あり 

p 39: 反復型ハッシュ関数の問題点について他の文献への参照があるとよい

**Comment by herumi** [comment]
ご指摘ありがとうございます。TSL3.0は恥ずかしい間違いでした。
https://github.com/herumi/ango/commit/53687bbbdd80a2cc02e056c4baa041c2ca9b577b

RSAに後で紹介すると説明をつけました。
https://github.com/herumi/ango/commit/bb61afd72d2fac81277b6d88e1a7b4dcfa1282a7

urandomを関数と呼ぶのは私もちょっと気が引けていたのですが大きい括りでは関数でいいかと思いました。デバイスに直します。
https://github.com/herumi/ango/commit/68e6f7daacb90d5b4f3cb633067980c65d354902

他の文献は後で調べます。たとえばどのようなものだとよいでしょうか。

**Comment by haruyama** [comment]
[Cryptography Engineering](https://www.schneier.com/book-ce.html) に 5.3 Weaknesses of Hash Functions という章があります.

**Comment by herumi** [comment]
ありがとうございます。参考にいたします。webで見られる資料もないか探してみます。

**Comment by haruyama** [comment]
Cryptography Enginnering で上げられているのは以下の2つです. (記事の中身のチェックまではしてません). 
- [Length extension attack - Wikipedia, the free encyclopedia](http://en.wikipedia.org/wiki/Length_extension_attack)
- Partial-Message Collision

5.4 Fixing the Weeknesses で 修正が上げられています
- h(h(m) || m)
- h(h(0^b || m)) : b は規定にある圧縮関数のブロック長
- SHA-224, SHA-384 のような 出力を truncate したものを利用
  - SHA-512/256 SHA-512/224 の制定より前の本です

また 5.4 の最初のほうに SHA-3 標準では 弱点についての言及がある(制定前です)と記述があります.

**Comment by herumi** [comment]
詳しい解説ありがとうございます。
http://www.ieice-hbkb.org/files/01/01gun_03hen_04.pdf
が日本語でとっかかりとして良さそうだったのでこれにしようと思います。

**Comment by haruyama** [comment]
:smile:
